georgian_woman_names = [
    "ნინო",
    "მარიამი",
    "სოფიო",
    "თამარი",
    "ელისო",
    "ეკატერინე",
    "ანა",
    "ნათია",
    "ქეთი",
    "მაია",
    "მეგი",
    "ელენე",
    "ქრისტინე",
    "მარი",
    "დიანა",
    "თინათინი",
    "თამთა",
    "სალომე",
    "ელენა",
    "ხატია",
]


common_interests = [
    "Travel",
    "Music",
    "Fitness",
    "Cooking",
    "Movies",
    "Reading",
    "Sports",
    "Pets",
    "Art",
    "Photography",
    "Gaming",
    "Outdoors",
    "Food",
    "Dancing",
    "Fashion",
    "Volunteering",
    "Technology",
    "Yoga",
    "Gardening",
    "Writing",
    "Hiking",
    "Cycling",
    "Meditation",
    "Crafts",
    "DIY Projects",
    "Languages",
    "Theater",
    "Anime",
    "Board Games",
    "Podcasts",
    "Running",
    "Surfing",
    "Snowboarding",
    "Karaoke",
    "Collecting",
    "Astronomy",
    "Fishing",
    "Martial Arts",
    "Scuba Diving",
    "History",
]
