from enum import Enum


class VerificationState(str, Enum):
    AWAITING_MEDIA_SUBMISSION = 'AWAITING_MEDIA_SUBMISSION'
    VERIFICATION_IN_PROGRESS = 'VERIFICATION_IN_PROGRESS'
    VERIFICATION_FAILED = 'VERIFICATION_FAILED'
    VERIFIED = 'VERIFIED'
    PROCESSING_MEDIA = 'PROCESSING_MEDIA'
    PROCESSING_FAILED = 'PROCESSING_FAILED'
    READY_FOR_USE = 'READY_FOR_USE'
